name: MeuFluxoDeTrabalho
on:
  push:
    branches:
      - main

jobs:
  meu_job:
    runs-on: ubuntu-latest
    steps:
      - name: Passo de exemplo
        run: echo "Este é um passo de exemplo no GitHub Actions"
